CREATE TABLE PAIS(
    id_pais SERIAL NOT NULL,
    nombre_pais VARCHAR(50) NOT NULL,
    CONSTRAINT PK_PAIS PRIMARY KEY(id_pais)
);

CREATE TABLE ESTADIO(
    id_estadio SERIAL NOT NULL,
    nombre_estadio VARCHAR(50) NOT NULL,
    capacidad VARCHAR(50) NOT NULL,
    CONSTRAINT PK_ESTADIO PRIMARY KEY (id_estadio)
);

CREATE TABLE LIGA(
    id_liga SERIAL NOT NULL,
    id_pais INT4 NOT NULL,
    nombre_liga VARCHAR(50) NOT NULL,
    CONSTRAINT PK_LIGA PRIMARY KEY (id_liga)
);


CREATE TABLE EQUIPO (
    id_equipo SERIAL NOT NULL,
    id_liga  INT4 NOT NULL,
    id_estadio INT4 NOT NULL,
    nombre_equipo  VARCHAR(50) NOT NULL,
    CONSTRAINT PK_EQUIPO PRIMARY KEY (id_equipo)
);

CREATE TABLE PERSONA(
    id_persona SERIAL NOT NULL,
    id_pais INT4 NOT NULL,
    nombre_persona VARCHAR(50) NOT NULL,
    apellido_persona VARCHAR(50) NOT NULL,
    documento_identidad VARCHAR(50) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    CONSTRAINT PK_PERSONA PRIMARY KEY (id_persona)
);

CREATE TABLE POSICION(
    id_posicion SERIAL NOT NULL,
    nombre_posicion VARCHAR(50) NOT NULL UNIQUE,
    CONSTRAINT PK_POSICION PRIMARY KEY (id_posicion)
);


CREATE TABLE JUGADOR(
    id_jugador SERIAL NOT NULL,
    id_persona INT4 NOT NULL,
    id_posicion INT4 NOT NULL,
    id_equipo INT4 NOT NULL,
    salario FLOAT4 NOT NULL,
    CONSTRAINT PK_JUGADOR PRIMARY KEY(id_jugador)
);

CREATE TABLE ENTRENADOR(
    id_entrenador SERIAL NOT NULL,
    id_persona INT4 NOT NULL,
    id_equipo INT4 NOT NULL UNIQUE,
    salario FLOAT4 NOT NULL,
    CONSTRAINT PK_ENTRENADOR PRIMARY KEY(id_entrenador)
);


/** CONSTRAINT DE LLAVES FORANEAS*/
alter table LIGA
   ADD CONSTRAINT FK_LIGA_REFERENCE_PAIS FOREIGN KEY (id_pais)
      REFERENCES PAIS (id_pais)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

alter table EQUIPO
   ADD CONSTRAINT FK_EQUIPO_REFERENCE_LIGA FOREIGN KEY (id_liga)
      REFERENCES LIGA (id_liga)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

alter table EQUIPO
   ADD CONSTRAINT FK_EQUIPO_REFERENCE_ESTADIO FOREIGN KEY (id_estadio)
      REFERENCES ESTADIO (id_estadio)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PERSONA
    ADD CONSTRAINT FK_PERSONA_REFERENCE_PAIS FOREIGN KEY (id_pais)
    REFERENCES PAIS (id_pais)
    ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE JUGADOR
    ADD CONSTRAINT FK_JUGADOR_REFERENCE_PERSONA FOREIGN KEY (id_persona)
    REFERENCES PERSONA (id_persona)
    ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE JUGADOR
    ADD CONSTRAINT FK_JUGADOR_REFERENCE_EQUIPO FOREIGN KEY (id_equipo)
    REFERENCES EQUIPO (id_equipo)
    ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE JUGADOR
    ADD CONSTRAINT FK_JUGADOR_REFERENCE_POSICION FOREIGN KEY (id_posicion)
    REFERENCES POSICION (id_posicion)
    ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ENTRENADOR
    ADD CONSTRAINT FK_ENTRENADOR_REFERENCE_PERSONA FOREIGN KEY (id_persona)
    REFERENCES PERSONA (id_persona)
    ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ENTRENADOR
    ADD CONSTRAINT FK_ENTRENADOR_REFERENCE_EQUIPO FOREIGN KEY (id_equipo)
    REFERENCES EQUIPO (id_equipo)
    ON DELETE RESTRICT ON UPDATE RESTRICT;




/** INSERTS */

INSERT INTO PAIS (id_pais,nombre_pais) VALUES ("1","ARGENTINA");
INSERT INTO PAIS (id_pais,nombre_pais) VALUES ("2","ESPAÑA");
INSERT INTO PAIS (id_pais,nombre_pais) VALUES ("3","ALEMANIA");
INSERT INTO PAIS (id_pais,nombre_pais) VALUES ("4","INGLATERRA");
INSERT INTO PAIS (id_pais,nombre_pais) VALUES ("5","ITALIA");
INSERT INTO PAIS (id_pais,nombre_pais) VALUES ("6","VENEZUELA");